version: "3.8"

services:
    app:
        build: .
        container_name: quiz_laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - laravel_network

    db:
        image: mysql:latest
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3308:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel_network

networks:
    laravel_network:

volumes:
    mysql_data:
